### ISSUE TITLE
Update cron command

### ISSUE THREAD

**Issue by russelg** [jhs7jhs/ichika-janken-auto#1]
Due to janken being playable 3 times a day now, perhaps a new cron rule is needed.

`1 10,15,20 * * *` seems like it fits the times.

**Comment by hyunsikjeong** [comment]
Resolved in: https://github.com/jhs7jhs/ichika-janken-auto/commit/f597480223cbef6e72c2dfe74d66aaa481a08e11
Thank you for opening the issue.
Actually I've already applied that new rule on my machine, but I forgot to update it on README. 😅
